#!/usr/bin/env python3

import time
import setproctitle
import threading as th
from core.redis2psql import redis2psql
from psql.dbConnServer import dbConnServer
from core.debug import debug


REDIS_PWD = "Q@@bcd!234##!"
PROC_NAME = "redis2psql"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
# -- dev box --
if debug.is_dev_box():
   REDIS_HOST = "localhost"
   REDIS_PORT = 16379

# -- global --
REDIS_CONF = {"HOST": REDIS_HOST, "PORT": REDIS_PORT, "PWD": REDIS_PWD}
PSQL_DB = dbConnServer.getConnection()

__redis2psql: redis2psql = redis2psql(redisConf=REDIS_CONF, psqlConn=PSQL_DB)
__redis2psqlTh: th.Thread = th.Thread(target=__redis2psql.run, args=())


def main():
   __redis2psqlTh.start()
   while True:
      try:
         time.sleep(8.0)
         print("main_loop")
         if __redis2psqlTh.is_alive():
            print("__redis2psqlTh.is_alive")
      except Exception as e:
         print(e)
         time.sleep(16.0)


# -- -- start here -- --
if __name__ == "__main__":
   setproctitle.setproctitle("red2psqlRunr")
   main()
