#!/usr/bin/env python3

import redis
import configparser as _cp
from core.debug import debug

# -- -- -- -- mark redis db's with text headers -- -- -- --
# /00_EDGE_README_00 :: /00_SERVER_README_00 :: /00_READS_README_00
#

INI: _cp.ConfigParser = _cp.ConfigParser()
INI.read("conf/redis2psql.ini")

HOST_PORT_KEY = "REDIS_PROD"
if debug.is_dev_box():
   HOST_PORT_KEY = "REDIS_DEV"
# -- -- -- -- -- --
host = INI.get(HOST_PORT_KEY, "HOST")
port: int = INI.getint(HOST_PORT_KEY, "PORT")
pwd = INI.get("REDIS", "PWD")

RED: redis.Redis = redis.Redis(host=host, port=port, password=pwd)
if not RED.ping():
   print("RedNoPong")
   exit(1)


README_KEY = "README"


RED.select(0)
d = {README_KEY: "This key is placed to mark the use of database 0 /"
   " holds onprem server device(s) diag info"}
key = "![_SERVER_DIAG_DB_]"
RED.delete(key)
RED.hset(key, mapping=d)


RED.select(1)
d = {README_KEY: "This key is placed to mark the use of database 1 /"
   " holds edge device(s) diag info"}
key = "![_EDGE_DIAG_DB_]"
RED.delete(key)
RED.hset(key, mapping=d)


RED.select(2)
d = {README_KEY: "This key is placed to mark the use of database 2 /"
   " holds system meter/endpoint reads"}
key = "![_READS_DB_]"
RED.delete(key)
RED.hset(key, mapping=d)
