#!/usr/bin/env python3

import json, time, os, sys
import configparser as _cp, redis, setproctitle
from psycopg2.extensions import connection as _psql_conn
from flask import Flask, render_template, request as req, make_response
try:
   from api.apiOps import apiOps
   from core.debug import debug
   from psql.dbConnServer import dbConnServer
   from core.logProxy import logProxy
   from api.dbEdit import dbEdit
except Exception as e:
   print(e)
   ROOT_DIR: str = os.getcwd()
   os.chdir("../")
   _p = os.getcwd()
   print(_p)
   sys.path.insert(0, _p)
   from api.apiOps import apiOps
   from core.debug import debug
   from psql.dbConnServer import dbConnServer
   from core.logProxy import logProxy
   from api.dbEdit import dbEdit
   os.chdir(ROOT_DIR)


START_INI_PATH = "start_ini"
if not os.path.islink(START_INI_PATH):
   print(f"START_INI_SIMLINK_NOT_FOUND: {START_INI_PATH}")
   exit(1)
print(f"\nSTART_INI_SIMLINK_FOUND: {START_INI_PATH}")


# -- load ini file --
WEBUI_INI: _cp.ConfigParser = _cp.ConfigParser()
WEBUI_INI.read(START_INI_PATH)
WEBUI_PORT: int = WEBUI_INI.getint("WEBUI", "PORT")
WANURL_GPIO: str = WEBUI_INI.get("WAN_ACCESS", "GPIO_UI")

# -- -- -- --
PSQL_CONN_CLOSED: bool = False
PSQL_CONN_STR = WEBUI_INI.get("PSQL", "CONN_STR")
print("\n-- [ CONNECTING TO PSQL ] --")
print(f" -> PSQL_CONN_STR: {PSQL_CONN_STR}")
PSQL_CONN: _psql_conn = dbConnServer.getConnection(PSQL_CONN_STR)
if PSQL_CONN is None:
   print("PSQL_CONN_IS_NONE")
   exit(100)

if PSQL_CONN.closed:
   PSQL_CONN_CLOSED = True
   print("PSQL_CONN is closed!\n")
   exit(101)
else:
   print("PSQL_CONN_OK\n")


RED_SEC: _cp.SectionProxy = WEBUI_INI["REDIS"]
REDIS: redis.Redis = redis.Redis(host=RED_SEC.get("HOST")
   , port=RED_SEC.getint("PORT"), password=RED_SEC.get("PWD"))
if not REDIS.ping():
   print("RedisBadPing!")
   exit(2)


CTYPE_JSON = "text/json"
CTYPE_TEXT = "text/plain"


APP_NAME = "omms-webui"
app = Flask(APP_NAME
   , static_url_path=""
   , static_folder="www"
   , template_folder="www")


@app.route("/", methods=["GET"])
@app.route("/home", methods=["GET"])
def index():
   return render_template("index.html", _wanurl_gpio=WANURL_GPIO)


"""
   "/api/get/list-reports";
"""
@app.route("/api/get/<item>", methods=["GET"])
def apiget(item):
   buffout = ""; errcode = 200; CTYPE = "text/plain"
   # -- create api object and pass the call --
   if item == "list-reports":
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR)
      buffout = apiops.list_reports()
      CTYPE = CTYPE_JSON
   elif item == "clients":
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      buffout = apiops.list_clients()
      CTYPE = CTYPE_JSON
   elif item == "client_circuits":
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      clttag: str = req.args["clttag"]
      buffout = apiops.list_client_circuits(clttag)
      CTYPE = CTYPE_JSON
   elif item == "redis_data":
      # url = `/api/get/redis_data/?dbidx=2&keys=[${sp}]`;
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      dbidx: int = int(req.args["dbidx"])
      keys: str = req.args["keys"]
      if keys[0] != "[" or keys[-1] != "]":
         buffout = "BadDataWrapper"; errcode = 566
      else:
         tmp: str = keys[1:-1]
         buffout = apiops.read_redis(dbidx, tmp.split("|"))
         buffout = json.dumps(buffout)
         CTYPE = CTYPE_JSON
   elif item == "utcnow_time":
      utcnow_time = int(time.time())
      buffout = {"utcnow_time": utcnow_time}
      buffout = json.dumps(buffout)
      CTYPE = CTYPE_JSON
   elif item == "clt-cir-history":
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      buffout = apiops.clt_cir_history()
      CTYPE = CTYPE_JSON
   elif item == "client_kwhrs":
      dts = req.args["dts"]
      cirs = req.args["cirs"]
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      buffout = apiops.clt_kwhrs(dts, cirs)
      CTYPE = CTYPE_JSON
   elif item == "overview":
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      buffout = apiops.overview()
      CTYPE = CTYPE_JSON
   else:
      buffout = ""; errcode = 404
   # -- -- return data -- --
   return buffout, errcode, {"content-type": CTYPE}

@app.route("/api/post/<item>", methods=["POST"])
def apipost(item):
   try:
      CTYPE = "text/plain"
      buffout = ""; errcode = 200
      if item == "monthly-report":
         y: str = req.values["year"]
         m: str = req.values["month"]
         apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
         err, val = apiops.set_report_job(item, y, m)
         if err == 0:
            buffout = json.dumps({"ERR": 0, "REPORT_ID": val})
         if err == 1 and val == 0:
            buffout = json.dumps({"ERR": 1, "VAL": 0})
         CTYPE = CTYPE_JSON
      else:
         pass
      # -- -- return data -- --
      return buffout, errcode, {"content-type": CTYPE}
   except Exception as e:
      logProxy.log_exp(e)

@app.route("/api/get/meters/<args>", methods=["GET"])
def apiget_meters(args):
   try:
      tag, val = args.split(":")
      errcode = 200; CTYPE = "text/json"
      apiops: apiOps = apiOps(INI=WEBUI_INI, conn_str=PSQL_CONN_STR, red=REDIS)
      buffout = apiops.list_client_meters(clt_dbid=int(val))
      # -- -- return data; errcode = 404 -- --
      return buffout, errcode, {"content-type": CTYPE}
   except Exception as e:
      logProxy.log_exp(e)
      return str(e)

@app.route("/dbedit/<path:action>", methods=["GET", "POST", "DELETE"])
def dbedit(action):
   hdrs = {"AppServer": "dbEdit ver.: 0.0.3"}
   try:
      _dbedit: dbEdit = dbEdit(conn_str=PSQL_CONN_STR, action=action, req=req)
      act_run_rval = _dbedit.run_action()
      if act_run_rval == 0:
         _ctype = "text/json"
         _bout, _err = _dbedit.buffout, _dbedit.buffout_error
      else:
         _ctype = "text/json"
         _bout, _err = _dbedit.buffout, _dbedit.buffout_error
      # -- return --
      hdrs["content-type"] = _ctype
      return _bout, _err, hdrs
   except Exception as e:
      hdrs["content-type"] = "text/exception"
      print(e)
      return str(e), 555, hdrs

@app.route("/state-info")
def state_info():
   hdrs = {"AppServer": "dbEdit ver.: 0.0.3", "content-type": "text/json"}
   try:
      redis_ping: bool = REDIS.ping()
      d: {} = {"PSQL_CONN_STR": PSQL_CONN_STR
         , "REDIS_PING": redis_ping, "PSQL_CONN_CLOSED": PSQL_CONN_CLOSED}
      # -- return --
      return json.dumps(d), 200, hdrs
   except Exception as e:
      print(e)

@app.route("/logout")
def _exit():
   return "EXIT_OK"


# == == == == == == == == == == == == == == == == == == == == == == == == == ==
# -- -- [ start app here ] -- --
if __name__ == "__main__":
   setproctitle.setproctitle(APP_NAME)
   app.run(host="0.0.0.0", port=WEBUI_PORT)
# == == == == == == == == == == == == == == == == == == == == == == == == == ==
