#!/bin/bash

cd ..
chmod +x server
./server
if [ $? != 0 ]; then
  echo "BadServerRun"
fi

# sleep a bit
sleep 4

# start redis2psql
chmod +x redis2psql_bot
./redis2psql_bot

sleep 4

# start backendops_bot
#chmod +x backendops_bot
#./backendops_bot
